### ISSUE TITLE
Error: Could not find minitest-5.11.3 in any of the sources

### ISSUE THREAD

**Issue by ghost** [ColaMakerspace/ColaMakerspace.github.io#12]
Getting this error on `jekyll build`:

```
C:\Users\alexl\Documents\code\html\ColaMakerspace.github.io>jekyll build
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize': 
Could not find minitest-5.11.3 in any of the sources (Bundler::GemNotFound)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.8.1/exe/jekyll:11:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'

C:\Users\alexl\Documents\code\html\ColaMakerspace.github.io>
```
Did anybody else run into this before and resolve this successfully? I found [this](https://github.com/seattlerb/minitest/issues/730) but... it does not appear to have easy solution.  Running on Windows.

**Comment by DallasEpperson** [comment]
What happens if you use the `bundle exec jekyll serve` command instead?

**Comment by ghost** [comment]
Yup. That did it. 
At first it told me
```
Could not find minitest-5.11.3 in any of the sources
Run `bundle install` to install missing gems.
```
so I did run `bundle install` and now your command works. Thanks!
